### ISSUE TITLE
problem with sf_to_df

### ISSUE THREAD

**Issue by mdsumner** [dcooley/sfheaders#61] opened 2020-03-05 05:09 UTC
There an issue with polygon/line encoding as data frame, here the polygon_id is incremented incorrectly (it's not clear to me if IDs generally are "global" or "within group hierarchy", but it looks like the latter (i.e. IDs reset within top-level, but not every level). 

```R
x <- silicate::minimal_mesh
library(sfheaders)
library(dplyr)
sf_to_df(x) %>% tibble::as_tibble()
# A tibble: 19 x 6
   sfg_id multipolygon_id polygon_id linestring_id     x     y
    <dbl>           <dbl>      <dbl>         <dbl> <dbl> <dbl>
 1      1               1          1             1  0     0   
 2      1               1          1             1  0     1   
 3      1               1          1             1  0.75  1   
 4      1               1          1             1  1     0.8 
 5      1               1          1             1  0.5   0.7 
 6      1               1          1             1  0.8   0.6 
 7      1               1          1             1  0.69  0   
 8      1               1          1             1  0     0   
 9      1               1          2             1  0.2   0.2 
10      1               1          2             1  0.5   0.2 
11      1               1          2             1  0.5   0.4 
12      1               1          2             1  0.3   0.6 
13      1               1          2             1  0.2   0.4 
14      1               1          2             1  0.2   0.2 
15      2               2          1             1  0.69  0   
16      2               2          1             1  0.8   0.6 
17      2               2          1             1  1.1   0.63
18      2               2          1             1  1.23  0.3 
19      2               2          1             1  0.69  0 
```

Above, `polygon_id` should be constant at 1. But `linestring_id` should change (at row 9) to differentiate the hole in the first feature. 

```R
x1 <- sf_to_df(x) %>% tibble::as_tibble() %>% 
  sf_multipolygon(x  = "x", y = "y", linestring_id = "linestring_id",  
                  polygon_id = "polygon_id", multipolygon_id = "multipolygon_id")
library(sf)
plot(x1)

```

![image](https://user-images.githubusercontent.com/4107631/75949745-496e7780-5efb-11ea-9aa3-941b09ed4d8e.png)

This is a fix (for this example,  not a general one). 

```R

tab <- sf_to_df(x) %>% tibble::as_tibble() 
tab$linestring_id <- tab$polygon_id
tab$polygon_id <- 1
x2 <- tab %>% 
  sf_multipolygon(x  = "x", y = "y", linestring_id = "linestring_id",  
                  polygon_id = "polygon_id", multipolygon_id = "multipolygon_id")
plot(x2)
```

![image](https://user-images.githubusercontent.com/4107631/75949773-5e4b0b00-5efb-11ea-9306-5336ed0eacf6.png)

In related matters, ~I think you should~  - I hope you also consider (I'm thinking about this atm) -  whether group IDs always increment or reset within groups (not sure it matters, but I settled on a run-length encoding in gibble, with *subobjects* identified for multipolygons. It means you need some grouping handling to restore the sfheader-alike df inputs, and I'm not on top of it atm, been meaning to see the relationship properly here - it would be neat if we shared the gibble (or similar) as a compact representation of what sfheaders treats as encoding).

**Comment by mdsumner** [comment] 2020-03-05 05:25
As a user we can't tell immediately that the above is broken, but with this example we can: 

```R
x <- silicate::inlandwaters
library(sfheaders)
library(dplyr)
sf_to_df(x) %>% tibble::as_tibble() %>% 
  sf_multipolygon(x  = "x", y = "y", linestring_id = "linestring_id",  
                  polygon_id = "polygon_id", multipolygon_id = "multipolygon_id")
x <- silicate::inlandwaters
library(sfheaders)
library(dplyr)
sf_to_df(x) %>% tibble::as_tibble() %>% 
  sf_multipolygon(x  = "x", y = "y", linestring_id = "linestring_id",  
                  polygon_id = "polygon_id", multipolygon_id = "multipolygon_id")

```

What it should be is

**Comment by dcooley** [comment] 2020-03-05 06:47
Thanks for reporting this - I can confirm it's an issue with the `sfc_` conversion, not the `sfg`

```r
devtools::install_github("hypertidy/silicate")

x <- silicate::minimal_mesh

str( x )

library(sf)

x[1, ]$geom[[1]]

sfheaders::sf_to_df( x[1, ] )
sfheaders::sfc_to_df( x[1, ]$geom )
sfheaders::sfg_to_df( x[1, ]$geom[[1]] )
```

**Comment by dcooley** [comment] 2020-03-05 07:23
fix and test in [this patch](https://github.com/dcooley/sfheaders/commit/3b314b99f7faa6f60108cc38ec234bc1fba36944)

**Comment by mdsumner** [comment] 2020-03-05 11:43
Sweet, thanks!  

FWIW, this is what I was going for after the st_remove_holes tweet, when I hit the bug: 

```R
x <- silicate::inlandwaters
#x <- silicate::minimal_mesh
library(dplyr)
library(sf)
library(sfheaders)
xx <- sf_to_df(x) %>% tibble::as_tibble() %>% 
  group_by(multipolygon_id, polygon_id)  %>% 
  filter(linestring_id == 1)  %>%   ## holes are linestring_id 1 within each polygon
  sf_multipolygon(x  = "x", y = "y",  polygon_id = "polygon_id", multipolygon_id = "multipolygon_id")
plot(xx)

```

I originally

**Comment by SymbolixAU** [comment] 2020-03-06 00:57
Also, I'm going to close this issue because It's now fixed, but happy to continue the discussion on another issue (if we implement `ignore_holes`), or over on your repo if you have suggestions / questions on how to integrate `sfheaders`

**Closed by SymbolixAU** 2020-03-06 00:57 UTC

**Comment by mdsumner** [comment] 2020-03-06 01:21
cool thanks (I don't see the need for `ignore_holes` that's not what I was going for)

**Comment by SymbolixAU** [comment] 2020-03-06 01:30
I thought it might be quicker to include it as a step inside the `sf_polygon()` construction, rather than having your `filter( linestring_id == 1 )` argument.

**Comment by mdsumner** [comment] 2020-03-06 01:51
Oh, to me the df modification is a general capacity, a pathway we can customise for all kinds of things - removing holes is just an example
